# Disable anonymous access
#listener 1883
#allow_anonymous true

# Point to password file
#password_file /etc/mosquitto/passwd

# Point to ACL file
#acl_file E:/2025/django/ccms/MQTT/etc/mosquitto/acl

# Optional for debug
#log_dest file /etc/mosquitto/mosquitto.log

#password_file E:/2025/django/ccms/MQTT/etc/mosquitto/passwd
#log_dest file E:/2025/django/ccms/MQTT/etc/mosquitto/mosquitto.log

# MQTT over TCP (won't work on Render, but included for completeness) 
listener 1883
protocol mqtt

# # MQTT over WebSocket (this is what Render will expose)
listener 9001
protocol websockets

# # Logging
log_dest file /mosquitto/log/mosquitto.log

# # Authentication
allow_anonymous true
password_file etc/mosquitto/passwd
acl_file etc/mosquitto/acl
